Update apiDefinition.swagger.json with First 5 actions
RjImpx/PowerPlatformConnectors pull request #16
Opened 2021-10-25 19:31 UTC by jokano12

---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

- [ ] I attest that the connector works and I verified by deploying and testing all the operations. 
- [ ] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [ ] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [ ] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [ ] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [ ] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

2021-10-26 01:08 UTC, lordlydon requested changes

2021-10-26 01:08 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +},
There is an extra closing curly bracket "}" here

2021-10-26 01:08 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                        "$ref": "#/definitions/EmailData"
The definition for EmailData is missing, and this endpoint returns an empty response.

2021-10-26 01:08 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                        "$ref": "#/definitions/AddressSaveData"
The definition for AddressSaveData is missing

2021-10-26 01:08 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                        "$ref": "#/definitions/AddressSaveData"
The definition for AddressSaveData is missing

2021-10-26 01:08 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                                    "$ref": "#/definitions/CommitteeMemberDetailData"
The definition for CommitteeMemberDetailData is missing

2021-10-26 01:08 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +    "/api/v1/Organizations/{Page Number}": {
I'm getting an error of a duplicated path when adding this to the current connector.
It seems to be because it clashes with the `/api/v1/Organizations/{id}` route.
Instead of defining this here, you can add the get to that existing path definition below.

2021-10-27 02:30 UTC, lordlydon requested changes
I added some more comments.
Please check the power automate connector cli tool, which provides a validate operation to check if there are errors or warnings with the connector swagger definition: https://github.com/Microsoft/PowerPlatformConnectors/tree/master/tools/paconn-cli#validate-a-swagger-json

2021-10-27 02:30 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +    "/api/v1/Organizations/{Page Number}": {
After adding this to the other route, you need to remove this one, or the error will still occur.

2021-10-27 02:30 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +    } },
There is an extra closing curly brace here

2021-10-27 02:30 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                    "name": "includeEmail",
When running paconn cli validate tool I'm getting this error for this property:
`The 'x-ms-summary' property is required.`

2021-10-27 02:30 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                    "name": "Term",
When running paconn cli validate tool I'm getting these errors for this property:
`The 'x-ms-summary' property is required.`
`The 'description' property is required.`

2021-10-27 02:30 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                    "name": "Position Codes",
When running paconn cli validate tool I'm getting these errors for this property:
`The 'x-ms-summary' property is required.`
`The 'description' property is required.`

2021-10-27 02:30 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +   "get": {
Can you fix the indentation here?

2021-10-27 02:30 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                    "name": "Name",
When running paconn cli validate tool I'm getting these errors for this property:
`The 'x-ms-summary' property is required.`

2021-10-27 02:30 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                    "name": "Include Details",
When running paconn cli validate tool I'm getting these errors for this property:
`The 'x-ms-summary' property is required.`
`The 'description' property is required.`

2021-10-27 02:30 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                    "name": "Tag",
When running paconn cli validate tool I'm getting these errors for this property:
`The 'x-ms-summary' property is required.`
`The 'description' property is required.`

2021-10-27 02:30 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                    "name": "Domain",
When running paconn cli validate tool I'm getting these errors for this property:
`The 'x-ms-summary' property is required.`

2021-10-27 02:30 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                "default": {
When running paconn cli validate tool I'm getting this error for this property:
`The 'default' response should not have schema definition. Schemas should be defined on expected responses only.`

2021-10-27 02:30 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                    "name": "ID Or Record Number",
When running paconn cli validate tool I'm getting this warning for this property:
`Encoding for path parameter 'ID Or Record Number' is missing, which might lead to invalid requests. Use \"x-ms-url-encoding\": \"single\" to ensure the value is URL encoded.`

2021-10-27 02:30 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                    "name": "ID Or Record Number",
When running paconn cli validate tool I'm getting this warning for this property:
`Encoding for path parameter 'ID Or Record Number' is missing, which might lead to invalid requests. Use \"x-ms-url-encoding\": \"single\" to ensure the value is URL encoded.`

2021-10-27 02:30 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                    "name": "First Name",
When running paconn cli validate tool I'm getting this warning for this property:
`Encoding for path parameter 'First Name' is missing, which might lead to invalid requests. Use \"x-ms-url-encoding\": \"single\" to ensure the value is URL encoded.`

2021-10-27 02:30 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                    "name": "Last Name",
When running paconn cli validate tool I'm getting this warning for this property:
`Encoding for path parameter 'Last Name' is missing, which might lead to invalid requests. Use \"x-ms-url-encoding\": \"single\" to ensure the value is URL encoded.`

2021-10-27 02:30 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                    "name": "Page Number",
When running paconn cli validate tool I'm getting this warning for this property:
`Encoding for path parameter 'Page Number' is missing, which might lead to invalid requests. Use \"x-ms-url-encoding\": \"single\" to ensure the value is URL encoded.`

2021-10-27 02:30 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                    "name": "ID Or Code",
When running paconn cli validate tool I'm getting this warning for this property:
`Encoding for path parameter 'ID Or Code' is missing, which might lead to invalid requests. Use \"x-ms-url-encoding\": \"single\" to ensure the value is URL encoded.`

2021-10-27 02:30 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                    "name": "Page Number",
When running paconn cli validate tool I'm getting this warning for this property:
`Encoding for path parameter 'Page Number' is missing, which might lead to invalid requests. Use \"x-ms-url-encoding\": \"single\" to ensure the value is URL encoded.`

2021-10-27 02:30 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                    "name": "Page Number",
When running paconn cli validate tool I'm getting this warning for this property:
`Encoding for path parameter 'id' is missing, which might lead to invalid requests. Use \"x-ms-url-encoding\": \"single\" to ensure the value is URL encoded."`

2021-11-02 20:24 UTC, closed without merging

2021-11-12 16:20 UTC, jokano12 commented
List All Individuals
Get List of Active Subscriptions for Individuals
Get Sub Committees
Get Positions by Committee
Get All Committees