Next 5 Actions
RjImpx/PowerPlatformConnectors pull request #18
Opened 2021-11-03 17:30 UTC by jokano12

---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

- [ ] I attest that the connector works and I verified by deploying and testing all the operations. 
- [ ] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [ ] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [ ] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [ ] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [ ] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

2021-11-06 14:07 UTC, LordLydon requested changes
Hi @jokano12, please check the definition of `CommitteeData`, and a few input parameters that should be in advanced options.
Thanks.

2021-11-06 14:07 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +    "CommitteeData": {
The definition of `CommitteeData` doesn't match the definition of the API response.
Please check http://abc.mpxdemo.com/api/help/ResourceModel?modelName=CommitteeData

2021-11-06 14:07 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +            "summary": "Get List of Active Subscriptions (Individuals)",
@RjImpx we don't use `(Individuals)` anywhere else, should this be changed to something like `Get Individual's Active Subscriptions`? This will retrieve all active subscriptions for a single individual based on the individual id passed as a parameter.

2021-11-06 14:07 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                    "name": "Old ID",
Please add `"x-ms-visibility": "advanced"`

2021-11-06 14:07 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                    "name": "Include Details",
Please add `"x-ms-visibility": "advanced"`

2021-11-08 15:49 UTC, RjImpx commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +            "summary": "Get List of Active Subscriptions (Individuals)",
@LordLydon @jokano12 "Get Individual's Active Subscriptions" sounds good to me

2021-11-08 17:52 UTC, jokano12 commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +    "CommitteeData": {
Matt gave me this definition to be used, which has updated descriptions.

2021-11-10 17:24 UTC, LordLydon approved these changes

2021-11-10 17:28 UTC, merged