PR 3
RjImpx/PowerPlatformConnectors pull request #19
Opened 2021-11-11 01:02 UTC by jokano12

References: (8)
PhoneDataset
PhoneSaveData
EventData
MembershipData
CustomFieldData
CommitteeMemberData
RegistrationData
RelationshipData

Actions: (10)
Get All Events
Get Organization Active Memberships
Get Organization Custom Field Values
Get Committee Information for an Individual
Add Phone to Individual
Get Individual Active Memberships
Get All Event Registrations Information for an Individual
Get Individual's Relationships
Update an Individual Email
Save Relationship for Organization

---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

- [ ] I attest that the connector works and I verified by deploying and testing all the operations. 
- [ ] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [ ] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [ ] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [ ] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [ ] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

2021-11-15 00:51 UTC, LordLydon requested changes

2021-11-15 00:51 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                        "description": "Country ID.",
Please add `Country -` prefix

2021-11-15 00:51 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                        "description": "Country Name.",
Please add `Country -` prefix here too

2021-11-15 00:51 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                        "description": "Two Letter ISO Code.",
Please add `Country -` prefix here too

2021-11-15 00:51 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                        "description": "Three Letter ISO Code.",
Please add `Country -` prefix here too

2021-11-15 00:51 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                        "description": "Country Code.",
Please add `Country -` prefix here too

2021-11-15 00:51 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                "$ref": "#/definitions/CommitteeData"
Please replace this with the content, adding the `Committe -` prefix to the descriptions

2021-11-15 00:51 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                        "items": {},
Please add the definition of the array items

2021-11-15 00:51 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                        "items": {},
Please add the definition of the array items here too

2021-11-15 00:51 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                        "items": {},
Please add the definition of the array items here too

2021-11-15 00:51 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                        "items": {},
Please add the definition of the array items here too

2021-11-15 00:51 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                            "items": {},
Please add the definition of the array items here too

2021-11-15 00:51 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                            "items": {},
Please add the definition of the array items here too

2021-11-15 00:51 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                            "items": {},
Please add the definition of the array items here too

2021-11-15 00:51 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                "items": {},
Please add the definition of the array items here too

2021-11-15 00:51 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                "description": "imageUrl"
Please fix this description

2021-11-15 00:51 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                    "properties": {
Please add `Event Locations -` prefix to these properties
Also add missing `title`s

2021-11-15 00:51 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                                "properties": {
Please add `Addresses -` prefix to these properties
Also add missing `title`s

2021-11-15 00:51 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                                        "properties": {
Please add `Country -` prefix

2021-11-15 00:51 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                        "$id": {
Please remove this property as it's not part of the response.
Check http://abc.mpxdemo.com/api/help/ResourceModel?modelName=CategoryData

2021-11-15 00:51 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                    "properties": {
please add `Categories -` prefix and missing `title`s

2021-11-15 00:51 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                    "properties": {
please add `Education Credits -` prefix to descriptions and missing `title`s

2021-11-15 00:51 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                    "properties": {
Please add `Uploads -` prefix to description and missing `title`s

2021-11-15 00:51 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                    "properties": {
Add `Related Products -` prefix to description and missing `title`s

2021-11-15 23:45 UTC, LordLydon requested changes
Hi,
            
Please keep in mind that the format for the description we are using is to add the property's name for nested arrays and objects, as there are many cases where both the root and nested objects have fields with the same name.

For example, `Code` and `Name` are properties that appear multiple times in a single response, and it can be confusing when trying to select the correct one in the Power Automate Flow Editor.
If the description shows `Code` and `Education Credits - Code`, it's easier to select the right option.

Another thing is that you seem to be updating only parts of the file, I would recommend copy & pasting the whole file to avoid problems with missing commas or duplicated lines.
And if you try to format the file and some indentations aren't fixed, it's a good sign that there is something missing/extra in the file.

2021-11-15 23:45 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                            "description": "Categories - Is Primary."
Missing comma `,`

2021-11-15 23:45 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                            "title": "Code
Missing closing quotation mark `"`

2021-11-15 23:45 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                            }
Missing comma `,`

2021-11-15 23:45 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                                "caption": {"type": "string", "description": "Caption".},
There is a dot `.` outside the quotation marks

2021-11-15 23:45 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                        "items": {
Please fix indentation

2021-11-15 23:45 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                "description": "Categories."
`description` and closing bracket `}` are duplicated here

2021-11-15 23:45 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                        "items": {
`items`, and `type` are duplicated

2021-11-15 23:45 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                                "properties": {
Please add `Subcategories -` prefix and missing `title`s

2021-11-15 23:45 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                    "properties": {
Please add `Terms -` prefix and add missing `title`s

2021-11-15 23:45 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                                "properties": {
Please add `Subcategories -` prefix and missing titles

2021-11-15 23:45 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                "properties": {
Please add `Related To Customer -` prefix

2021-11-15 23:45 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                            "properties": {
Please add `Addresses -` prefix

2021-11-15 23:45 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                                    "properties": {
Please add `Country -` prefix

2021-11-15 23:45 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                            "properties": {
Please add `Emails -` prefix

2021-11-15 23:45 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                            "properties": {
Please add `Phones -` prefix

2021-11-15 23:45 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +        "properties": {
Please add `Memberships -` prefix

2021-11-15 23:45 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                    "properties": {
Please add `Categories -` prefix and missing `title`s

2021-11-15 23:45 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                "properties": {
Please add `Event -` prefix

2021-11-15 23:45 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                            "properties": {
Please add `Locations -` prefix and missing `title`s

2021-11-15 23:45 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                                        "properties": {
Please add `Addresses -` prefix and missing `title`s

2021-11-15 23:45 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                                                "properties": {
Please add `Country -` prefix and missing `title`s

2021-11-15 23:45 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                            "properties": {
Please add `Custom Fields -` prefix and missing `title`s

2021-11-15 23:45 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                    "properties": {
Please add `Sessions -` prefix and missing `title`s

2021-11-15 23:45 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                    "properties": {
Please add `Bought Together With -` prefix and missing `title`s

2021-11-15 23:45 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                              "properties": {
Please add `Itemized Custom Fields -` prefix and missing `title`s

2021-11-15 23:45 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                              "properties": {
Please add `Product Categories -` prefix and missing `title`s

2021-11-15 23:45 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                "properties": {
There was a typo in my last comment, please replace `Committe` with `Committee`

2021-11-15 23:45 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                    "properties": {
Please add `Terms -` prefix

2021-11-15 23:45 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                                "properties": {
Please update prefix

2021-11-16 22:29 UTC, LordLydon requested changes
There are still some closing brackets missing, I'm getting this error when running paconn validate `Expecting ',' delimiter: line 13574 column 1 (char 525295)`

2021-11-16 22:29 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                                "properties": {
Please update the prefix here to `Subcategories -`

2021-11-17 19:35 UTC, LordLydon requested changes
I'm still getting the same error from paconn validate:
`Expecting ',' delimiter: line 13575 column 1 (char 526501)`

2021-11-18 23:44 UTC, LordLydon requested changes
The paconn errors are now fixed, and I could update the test connector. Checking the actions in the flow editor I found a couple of other issues, please check the comments.

2021-11-18 23:44 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +            "position": {
Please add missing title

2021-11-18 23:44 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +            "positionCode": {
Please add missing title

2021-11-18 23:44 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +            "startDate": {
Please add missing title

2021-11-18 23:44 UTC, lordlydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                                "title": ""
Please add missing title

2021-11-18 23:44 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                "title": "Event"
Please remove the title here as it's added to the name of the children properties.

2021-11-18 23:44 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                "title": "Related To Customer"
Please remove title here too

2021-11-18 23:44 UTC, LordLydon commented on certified-connectors/Impexium/apiDefinition.swagger.json
> +                                "title": "Address"
Please fix title here

2021-11-19 02:48 UTC, RjImpx commented
> Hi,
> 
> Please keep in mind that the format for the description we are using is to add the property's name for nested arrays and objects, as there are many cases where both the root and nested objects have fields with the same name.
> 
> For example, `Code` and `Name` are properties that appear multiple times in a single response, and it can be confusing when trying to select the correct one in the Power Automate Flow Editor. If the description shows `Code` and `Education Credits - Code`, it's easier to select the right option.
> 
> Another thing is that you seem to be updating only parts of the file, I would recommend copy & pasting the whole file to avoid problems with missing commas or duplicated lines. And if you try to format the file and some indentations aren't fixed, it's a good sign that there is something missing/extra in the file.

@jokano12 please make sure you submit PRs **ONLY** after running paconn validate

2021-11-20 14:59 UTC, LordLydon requested changes
I'm getting this error when I run paconn validate.
`Expecting property name enclosed in double quotes: line 5530 column 13 (char 217411)`

2021-11-23 14:10 UTC, LordLydon approved these changes

2021-11-23 14:59 UTC, merged